/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedFollowupsRouteImport } from './routes/_authenticated/followups'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedLedgerRouteImport } from './routes/_authenticated/ledger'
import { Route as AuthenticatedPartiesRouteImport } from './routes/_authenticated/parties'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedQuotationsRouteImport } from './routes/_authenticated/quotations'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDocDocIdRouteImport } from './routes/_authenticated/doc.$docId'
import { Route as AuthenticatedDocEditDocIdRouteImport } from './routes/_authenticated/doc.edit.$docId'
import { Route as AuthenticatedDocNewKindRouteImport } from './routes/_authenticated/doc.new.$kind'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowupsRoute = AuthenticatedFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLedgerRoute = AuthenticatedLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartiesRoute = AuthenticatedPartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotationsRoute = AuthenticatedQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocDocIdRoute = AuthenticatedDocDocIdRouteImport.update({
  id: '/doc/$docId',
  path: '/doc/$docId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocEditDocIdRoute =
  AuthenticatedDocEditDocIdRouteImport.update({
    id: '/doc/edit/$docId',
    path: '/doc/edit/$docId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocNewKindRoute = AuthenticatedDocNewKindRouteImport.update({
  id: '/doc/new/$kind',
  path: '/doc/new/$kind',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/followups': typeof AuthenticatedFollowupsRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/parties': typeof AuthenticatedPartiesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/products': typeof AuthenticatedProductsRoute
  '/quotations': typeof AuthenticatedQuotationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/doc/$docId': typeof AuthenticatedDocDocIdRoute
  '/doc/edit/$docId': typeof AuthenticatedDocEditDocIdRoute
  '/doc/new/$kind': typeof AuthenticatedDocNewKindRoute
}
export interface FileRoutesByTo {
  '/followups': typeof AuthenticatedFollowupsRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/parties': typeof AuthenticatedPartiesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/products': typeof AuthenticatedProductsRoute
  '/quotations': typeof AuthenticatedQuotationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/doc/$docId': typeof AuthenticatedDocDocIdRoute
  '/doc/edit/$docId': typeof AuthenticatedDocEditDocIdRoute
  '/doc/new/$kind': typeof AuthenticatedDocNewKindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/followups': typeof AuthenticatedFollowupsRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/ledger': typeof AuthenticatedLedgerRoute
  '/_authenticated/parties': typeof AuthenticatedPartiesRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/quotations': typeof AuthenticatedQuotationsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/doc/$docId': typeof AuthenticatedDocDocIdRoute
  '/_authenticated/doc/edit/$docId': typeof AuthenticatedDocEditDocIdRoute
  '/_authenticated/doc/new/$kind': typeof AuthenticatedDocNewKindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/followups'
    | '/invoices'
    | '/ledger'
    | '/parties'
    | '/payments'
    | '/products'
    | '/quotations'
    | '/settings'
    | '/doc/$docId'
    | '/doc/edit/$docId'
    | '/doc/new/$kind'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/followups'
    | '/invoices'
    | '/ledger'
    | '/parties'
    | '/payments'
    | '/products'
    | '/quotations'
    | '/settings'
    | '/'
    | '/doc/$docId'
    | '/doc/edit/$docId'
    | '/doc/new/$kind'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/followups'
    | '/_authenticated/invoices'
    | '/_authenticated/ledger'
    | '/_authenticated/parties'
    | '/_authenticated/payments'
    | '/_authenticated/products'
    | '/_authenticated/quotations'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/doc/$docId'
    | '/_authenticated/doc/edit/$docId'
    | '/_authenticated/doc/new/$kind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/followups': {
      id: '/_authenticated/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof AuthenticatedFollowupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ledger': {
      id: '/_authenticated/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AuthenticatedLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parties': {
      id: '/_authenticated/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof AuthenticatedPartiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations': {
      id: '/_authenticated/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AuthenticatedQuotationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doc/$docId': {
      id: '/_authenticated/doc/$docId'
      path: '/doc/$docId'
      fullPath: '/doc/$docId'
      preLoaderRoute: typeof AuthenticatedDocDocIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doc/edit/$docId': {
      id: '/_authenticated/doc/edit/$docId'
      path: '/doc/edit/$docId'
      fullPath: '/doc/edit/$docId'
      preLoaderRoute: typeof AuthenticatedDocEditDocIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doc/new/$kind': {
      id: '/_authenticated/doc/new/$kind'
      path: '/doc/new/$kind'
      fullPath: '/doc/new/$kind'
      preLoaderRoute: typeof AuthenticatedDocNewKindRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFollowupsRoute: typeof AuthenticatedFollowupsRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedLedgerRoute: typeof AuthenticatedLedgerRoute
  AuthenticatedPartiesRoute: typeof AuthenticatedPartiesRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedQuotationsRoute: typeof AuthenticatedQuotationsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDocDocIdRoute: typeof AuthenticatedDocDocIdRoute
  AuthenticatedDocEditDocIdRoute: typeof AuthenticatedDocEditDocIdRoute
  AuthenticatedDocNewKindRoute: typeof AuthenticatedDocNewKindRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFollowupsRoute: AuthenticatedFollowupsRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedLedgerRoute: AuthenticatedLedgerRoute,
  AuthenticatedPartiesRoute: AuthenticatedPartiesRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedQuotationsRoute: AuthenticatedQuotationsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDocDocIdRoute: AuthenticatedDocDocIdRoute,
  AuthenticatedDocEditDocIdRoute: AuthenticatedDocEditDocIdRoute,
  AuthenticatedDocNewKindRoute: AuthenticatedDocNewKindRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
