/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FollowupsRouteImport } from './routes/followups'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as PartiesRouteImport } from './routes/parties'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DocDocIdRouteImport } from './routes/doc.$docId'
import { Route as DocEditDocIdRouteImport } from './routes/doc.edit.$docId'
import { Route as DocNewKindRouteImport } from './routes/doc.new.$kind'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowupsRoute = FollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesRoute = PartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocDocIdRoute = DocDocIdRouteImport.update({
  id: '/doc/$docId',
  path: '/doc/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocEditDocIdRoute = DocEditDocIdRouteImport.update({
  id: '/doc/edit/$docId',
  path: '/doc/edit/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocNewKindRoute = DocNewKindRouteImport.update({
  id: '/doc/new/$kind',
  path: '/doc/new/$kind',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/followups': typeof FollowupsRoute
  '/invoices': typeof InvoicesRoute
  '/ledger': typeof LedgerRoute
  '/parties': typeof PartiesRoute
  '/payments': typeof PaymentsRoute
  '/products': typeof ProductsRoute
  '/quotations': typeof QuotationsRoute
  '/settings': typeof SettingsRoute
  '/doc/$docId': typeof DocDocIdRoute
  '/doc/edit/$docId': typeof DocEditDocIdRoute
  '/doc/new/$kind': typeof DocNewKindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/followups': typeof FollowupsRoute
  '/invoices': typeof InvoicesRoute
  '/ledger': typeof LedgerRoute
  '/parties': typeof PartiesRoute
  '/payments': typeof PaymentsRoute
  '/products': typeof ProductsRoute
  '/quotations': typeof QuotationsRoute
  '/settings': typeof SettingsRoute
  '/doc/$docId': typeof DocDocIdRoute
  '/doc/edit/$docId': typeof DocEditDocIdRoute
  '/doc/new/$kind': typeof DocNewKindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/followups': typeof FollowupsRoute
  '/invoices': typeof InvoicesRoute
  '/ledger': typeof LedgerRoute
  '/parties': typeof PartiesRoute
  '/payments': typeof PaymentsRoute
  '/products': typeof ProductsRoute
  '/quotations': typeof QuotationsRoute
  '/settings': typeof SettingsRoute
  '/doc/$docId': typeof DocDocIdRoute
  '/doc/edit/$docId': typeof DocEditDocIdRoute
  '/doc/new/$kind': typeof DocNewKindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/followups'
    | '/invoices'
    | '/ledger'
    | '/parties'
    | '/payments'
    | '/products'
    | '/quotations'
    | '/settings'
    | '/doc/$docId'
    | '/doc/edit/$docId'
    | '/doc/new/$kind'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/followups'
    | '/invoices'
    | '/ledger'
    | '/parties'
    | '/payments'
    | '/products'
    | '/quotations'
    | '/settings'
    | '/doc/$docId'
    | '/doc/edit/$docId'
    | '/doc/new/$kind'
  id:
    | '__root__'
    | '/'
    | '/followups'
    | '/invoices'
    | '/ledger'
    | '/parties'
    | '/payments'
    | '/products'
    | '/quotations'
    | '/settings'
    | '/doc/$docId'
    | '/doc/edit/$docId'
    | '/doc/new/$kind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FollowupsRoute: typeof FollowupsRoute
  InvoicesRoute: typeof InvoicesRoute
  LedgerRoute: typeof LedgerRoute
  PartiesRoute: typeof PartiesRoute
  PaymentsRoute: typeof PaymentsRoute
  ProductsRoute: typeof ProductsRoute
  QuotationsRoute: typeof QuotationsRoute
  SettingsRoute: typeof SettingsRoute
  DocDocIdRoute: typeof DocDocIdRoute
  DocEditDocIdRoute: typeof DocEditDocIdRoute
  DocNewKindRoute: typeof DocNewKindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followups': {
      id: '/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof FollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties': {
      id: '/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof PartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$docId': {
      id: '/doc/$docId'
      path: '/doc/$docId'
      fullPath: '/doc/$docId'
      preLoaderRoute: typeof DocDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/edit/$docId': {
      id: '/doc/edit/$docId'
      path: '/doc/edit/$docId'
      fullPath: '/doc/edit/$docId'
      preLoaderRoute: typeof DocEditDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/new/$kind': {
      id: '/doc/new/$kind'
      path: '/doc/new/$kind'
      fullPath: '/doc/new/$kind'
      preLoaderRoute: typeof DocNewKindRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FollowupsRoute: FollowupsRoute,
  InvoicesRoute: InvoicesRoute,
  LedgerRoute: LedgerRoute,
  PartiesRoute: PartiesRoute,
  PaymentsRoute: PaymentsRoute,
  ProductsRoute: ProductsRoute,
  QuotationsRoute: QuotationsRoute,
  SettingsRoute: SettingsRoute,
  DocDocIdRoute: DocDocIdRoute,
  DocEditDocIdRoute: DocEditDocIdRoute,
  DocNewKindRoute: DocNewKindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
